PORT: 9000
PREFIX: api

# 正常token2小时
tokenExpire: 2
# 刷新过期时间为7天
refreshTokenExpire: 7

# 默认密码
defaultPassword: 123456

# 数据库配置
datasource:
  driverName: mysql
  host: localhost
  port: 3306
  database: business
  username: root
  password: chance..
  charset: utf8mb4
  logging: true

# Minio配置
MINIO_CONFIG:
  MINIO_ENDPOINT: '10.168.1.93'
  MINIO_PORT: 31397
  MINIO_ACCESSKEY: 'z6SFnUZjBD4RDUd0'
  MINIO_SECRETKEY: 'ZLfs07nCZ02SuHo1ABQsFdaFR5XnTxX7'
  MINIO_BUCKET: 'oa'

# 腾讯地图api
lbsKey: LW7BZ-NB7C5--QNDSX-VCZVT-D7FQ4

# 阿里oss存储(可直接使用)
aliyunOss:
  accessKeyId: 'LTAI4FmwbKtoErzJdwfJmcmd'
  accessKeySecret: 'bu5UZXAG2dXQ6G75bzTDXoTN1VcALv'
  endpointUrl: 'oss-cn-shenzhen'
  bucketUrl: 'https://an-jia-shop.oss-cn-shenzhen.aliyuncs.com'
  bucketName: 'an-jia-shop'
  imgDefaultSize: 5
  supportImgTypes: ['.png', '.jpg', '.gif', '.jpeg']
